name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Greeting Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.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 }}
          event-type: new-contributor
          client-payload: '{"username": "ajayjp123"}'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python Script
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
      - name: Execute Python Script
        run: python my_script.py

